[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
multisig = "CQGjzX8tN5AdEjzRkRJoVsxQtbdYpwvFJ8nVm6SQDJJp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mykyta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
